### ISSUE TITLE
Add retry logic into django-cockroachdb adapter

### ISSUE THREAD

**Issue by apantel** [cockroachdb/django-cockroachdb#119]
Provide a decorator allowing users to retry transactions. Handle nesting appropriately.

**Comment by timgraham** [comment]
If I understand correctly, you're proposing to put the decorator from https://github.com/cockroachdb/examples-orms/pull/92 in this library. That's not the sort of code that typically lives in a Django database adapter. Perhaps it would better to have a separate library of "cockroachdb helpers" if that sort of thing is needed.

**Comment by apantel** [comment]
That is what I meant. It's not a must-do if you don't think it belongs with the adapter.

**Comment by awoods187** [comment]
we've found that transaction retrys are confusing to our users because they are more likely to happen in CockroachDB (due to serializable isolation as well as multi-region clusters). We've had success incorporating this into the ORM in the past to make life easier for developers

**Comment by vy-ton** [comment]
> That's not the sort of code that typically lives in a Django database adapter.

@timgraham I wasn't around for the initial conversation, but can you share more insights into why retry logic shouldn't live within the database adapter?

**Comment by timgraham** [comment]
I'm hesitant to include something like the `retry_on_exception` decorator because database adapters generally don't contain any public API code that user projects can import. Are most all CockroachDB projects using it? As I mentioned before, it could also live in a separate library.

As to whether the adapter could automatically do retries, I'm not sure if it's feasible. Django's philosophy is that transactions retries is an application concern. I've only come across [one case](https://github.com/cockroachdb/django-cockroachdb/issues/132) in Django's test suite where retries needed to be added to the adapter. I feel like automatic retries might be a sort of magical behavior that might mask other problems but I could be wrong about that.

**Comment by timgraham** [comment]
Closing as "won't fix."
