### ISSUE TITLE
Test tables will be truncated unless RUNNING_COCKROACH_BACKEND_TESTS is set

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/django-cockroachdb#140]
I was trying out the django-cockroachdb driver with a project last week.
I has a [fairly strange test setup](https://github.com/chrisseto/pycon2020-big-o-no) were I was populating the main DB ahead of time and using the main DB as the test DB.

I found that all my tests failed to find data with no explanation, this was quite frustrating.
It took a bit of digging but I found that Django's test framework will implicitly truncate all tables for you if `supports_transactions` is set to `False`.
Even if I was aware of that fact I would have over looked it for a SQL driver 🙂 

I'm not sure I have a recommended resolution to the problem but perhaps documenting this behavior would save others some time?

**Comment by timgraham** [comment]
This is documented (indirectly) in the "Known issues and limitations" section of the README, "Django's TestCase works like TransactionTestCase. That is, transactions aren't used to speed up the former." Since your use case isn't officially supported, I don't think additional documentation is required. Also, the limitation will be lifted with CockroachDB 20.1 where savepoints are supported. Thanks for your feedback.
