### ISSUE TITLE
Future Compatibility 

### ISSUE THREAD

**Issue by dickermoshe** [cockroachdb/django-cockroachdb#275]
Do you see CockroachDB in the future being completely compatible with Django migrations ?
This entire repo is pretty pointless without it

**Comment by timgraham** [comment]
Some schema-related enhancement requests for CockroachDB are linked from the "Known issues and limitations" section of the [README](https://github.com/cockroachdb/django-cockroachdb#readme). You could comment on those corresponding issues if they're blocking you so that CockroachDB developers may prioritize accordingly. For now, you do need to avoid certain migration operations that CockroachDB doesn't support.
